#!/bin/bash

alias ..='cd ..'
alias :E='vim +:E'
alias :e='vim'
alias E='vim +:E'
alias ZQ='exit'
alias ZZ='exit'
alias bd='date +%d%m%Y'
alias c='clear && ls'
alias cal='cal -Ym'
alias d='cd'
alias e='vim'
alias g='git'
alias l='ls'
alias lesla='ls -hla | less'
alias ls='ls --color=auto -A'
alias lsg='ls | grep'
alias m='make -j16'
alias minecraft='java -jar ~/Downloads/Minecraft.jar'
alias mle='m 2>&1 | less'
alias pu='phpunit'
alias rmr='rm -rf'
alias sl='ls'
alias ta='tmux -2 attach'
alias tm='tmux -2'
alias tracker='/opt/tracker/tracker.sh'
alias tt='tmux -2'
which nvim && alias vim='nvim'
