#!/usr/bin/env ruby

require 'barr'
require 'rubygems'

version = ">= 0.a"

class MixerBlock < Barr::Block
    def initialize opts={}
        super
        @volume = '100'
    end
    def get_volume
        `pamixer --get-volume`.chomp
    end
    def update!
        @volume = get_volume
        @output = @volume.to_s + '%'
    end
end

@manager = Barr::Manager.new

@manager.add Barr::Blocks::Bspwm.new icon: "\uf009", monitor: "eDP1", invert_focus_colors: true, align: :l, focus_markers: [' ', ' '], interval: 0.1

@manager.add Barr::Blocks::Battery.new fgcolor: '#000000', bgcolor: '#673AB7',show_remaining: true, align: :r, icon: "\uf242"
#@manager.add Barr::Blocks::Temperature.new fgcolor: '#000000', bgcolor: '#1DE9B6', align: :r, icon: "\uf185 Brno", location: '786869'
@manager.add MixerBlock.new fgcolor: '#000000', bgcolor: '#00FF00', align: :r, icon: "\uf028"
@manager.add Barr::Blocks::IP.new fgcolor: '#000000',bgcolor: '#CDDC39', align: :r, device: 'wlp3s0', icon: "\uf1eb"
@manager.add Barr::Blocks::Clock.new fgcolor: '#000000', bgcolor: '#D50000',icon: "\uf017", format: '%a %d %b %H:%M',show_remaining: true, align: :r

@manager.run!
