#! /bin/bash

sxhkd &

bspc config border_width            0
bspc config window_gap              0

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc rule -a "*" state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

feh --bg-fill ~/pictures/notebook_bg.jpg

for monitor in `xrandr -q | grep connected | sed s'/ .*//g'`; do
    bspc monitor -d 1 2 3 4 5 6 7 8 9 $monitor
    (ruby ~/dotfiles/bspwm/barr $monitor | lemonbar -f "Roboto Medium" -f "Font Awesome" $monitor)&
done

stalonetray
