#! /bin/bash

sxhkd &

bspc monitor `bspc query -M | head -n 1` -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "*" state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

feh --bg-fill ~/Pictures/notebook_bg.jpg
ruby /home/jasku/dotfiles/bspwm/barr | lemonbar -f "Roboto Medium" -f "Font Awesome"
