#!/bin/sh

block_timetrap() {
  echo "{ \"name\":\"timetrap\", \"full_text\":\"" $(~/.gem/ruby/2.6.0/bin/timetrap now 2>&1) "\"}"
}

block_online() {
  if ping -w 1 -c 1 1.1.1.1 2>/dev/null >/dev/null; then
    onlinestatus=" "
  else
    onlinestatus="offline"
  fi

  echo "{ \"name\":\"online\", \"full_text\":\"" $onlinestatus "\"}"
}

block_dirtywr() {
  busy="wr $(grep "Dirty:" /proc/meminfo | sed s'/Dirty://g')"
  bdcount=$(ls /sys/block | wc -l)
  if [ $bdcount -lt 3 ]; then
    busy=""
  fi
  echo "{ \"name\":\"dirtywr\", \"full_text\":\"" $busy "\"}"
}

i3status | {
  read VERSION
  echo $VERSION
  read START
  echo $START
  while :
  do
    LINE=$(head -n 1 | sed s/^,//)
    BLOCKS="$(block_dirtywr), $(block_online)"
    echo $LINE | jq -c ". |= [$BLOCKS] + ."
    echo ,
  done
}
