#!/usr/bin/sh

internet=wlp3s0
link=enp2s0

if [[ $(whoami) != "root" ]]; then
  echo "Please run $0 as root"
  exit 1
fi

ip link set up dev $link
ip addr add 10.0.0.1/24 dev $link
ip addr add fd00:dead:beef::1/64 dev $link
sysctl net.ipv4.ip_forward=1
sysctl net.ipv6.conf.default.forwarding=1
sysctl net.ipv6.conf.all.forwarding=1

iptables -t nat -A POSTROUTING -o $internet -j MASQUERADE
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $link -o $internet -j ACCEPT
