#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

parent_path="`readlink -nf $BASH_SOURCE`"
parent_path=${parent_path%/*}

for file in `ls $parent_path/bashrc.d/*.sh`; do
    . $file 2>&1 >/dev/null
done
